CREATE TABLE Product_images (
    ImageId BIGINT AUTO_INCREMENT PRIMARY KEY,
    ProductId BIGINT NOT NULL,
    ImageUrl VARCHAR(500) NOT NULL,
    IsPrimary TINYINT DEFAULT 0,
    SortOrder INT DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (ProductId) REFERENCES Products(ProductId) ON DELETE CASCADE
);

